### PR TITLE
Removed newlines to fix issue 641

### PR DESCRIPTION
**Pull request by CountOrlok**

### CODE REVIEW

**Comment by ckruse** [comment]
I'm sorry, but this fix isn't sufficient.

Wie added the newlines to avoid the most common error with markdown: missing newlines between blocks. This drastically reduced code blocks not rendered as code blocks. If you remove  them we have the same problem again.

I think what you actually have to do is look for the previous two characters and check if they're newlines. If yes, then don't add newlines. If no then add newlines. Do you agree?

**Comment by CountOrlok** [comment]
ACK. I did some additional testing and I think there is even more work required than you proposed, since inline code triggers a code block if followed by newline, which should not be the case either. 

_My code:_ `doSomething()`

_Some plain text._

This is really a mess.

**Comment by ckruse** [comment]
Heh, this is always the case when the textarea contains newlines. Pretty bugged. I check the complete textarea for newlines instead of just the selected test:

~~~
            else if(content.indexOf('\n') > -1) {
~~~

`content` should've been `selected`.

**Comment by CountOrlok** [comment]
I'm going to change this. We should also consider to replace `indexOf` with `includes` to check for existance. The method is now widely supported and using it improves readability.

            else if (selected.includes('\n')) {

Nevertheless, if we decide to do so, I'd recommend to add a polyfill for Internet Explorer and some older mobile browsers, until they're dead and buried. Your thoughts?

**Comment by ckruse** [comment]
Go for it. I trust your judgement.

**Pull request merged**
